title: Matt (IPv4) Cowley

meta:
  description: |
    Community Platform Manager @ DigitalOcean ğŸ¦ˆ
    Maintainer of cdnjs.com @ Cloudflare â›…ï¸
    Developer Relations @ js.org ğŸ“
    Open-source maintainer & avid supporter ğŸ’»

  keywords:
    - matt
    - cowley
    - matt cowley
    - ipv4
    - matt ipv4
    - mattipv4
    - matt ipv4 cowley
    - matt (ipv4) cowley
    - matt website
    - matt ipv4 website
    - ipv4 website
    - matt site
    - matt ipv4 site
    - ipv4 site
    - community
    - community management
    - community manager
    - open source
    - open-source
    - engineer
    - web dev
    - web development
    - web developer
    - frontend developer
    - backend developer
    - fullstack developer
    - frontend engineer
    - backend engineer
    - fullstack engineer
    - theatre
    - theater
    - technical
    - technician
    - tech
    - theatre technician
    - theater technician
    - theatre tech
    - theater tech

  banner: https://assets.mattcowley.co.uk/header/header.png
  icon: https://assets.mattcowley.co.uk/head/transp/goggles/head_t_g.png
  color: "#0069ff"
  url: https://mattcowley.co.uk/
  twitter: "@MattIPv4"

google:
  analytics: UA-113826252-1
#  adsense:
#    client: ca-pub-4266526051230566
#    slot: 9114202102

main:
  - title: "What I do:"
    size: h2
    items:
      - Community Platform Manager @ DigitalOcean ğŸ¦ˆï¸
      - Maintainer of cdnjs.com @ Cloudflare â›…
      - Developer Relations @ js.org ğŸ“
      - Open-source maintainer & avid supporter ğŸ’»

  - title: "Who I am:"
    size: h3
    items:
      - 20 y/o based near London, UK ğŸ“
      - Studying BSc Computing @ University ğŸ“

  - title: "What I'm interested in:"
    size: h3
    items:
      - Community Management, Developer Relations, Open-Source Advocacy ğŸ¥‘
      - Software Engineering, Full-stack Development (Node.js, Ruby on Rails, Vue.js) ğŸ–¥
      - Live Production, Live Broadcasting (Livestreaming, Radio, Theatre) ğŸ™
      - Stage Management, Production Electrics, Lighting ğŸ’¡

rail: []
#rail:
#  - title: "Education:"
#    content: |
#      * Studying BSc Computing @ University of Buckingham.
#      * AAB in Computer Science, Maths & Business Studies at A Level.
#      * 9 in Maths with an A in Additional Maths (FSMQ), Computing, Physics & Geography at GCSE.
#      * 8/6 in English Lit/Lang and a B in Biology, Chemistry, Art, French & RS at GCSE.

contact:
  email: me@mattcowley.co.uk
  links:
    - title: "**twitter**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://twitter.mattcowley.co.uk/

    - title: "**github**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://github.mattcowley.co.uk/

    - title: "**twitch**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://twitch.mattcowley.co.uk/

    - title: "**sponsors**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://sponsors.mattcowley.co.uk/

    - title: "**discord**_.mattcowley.co.uk_"
      username: ""
      url: https://discord.mattcowley.co.uk/
