title: Matt (IPv4) Cowley

meta:
  description: |
    Community Platform Manager @ DigitalOcean ğŸ¦ˆ
    Maintainer of cdnjs.com @ Cloudflare â›…ï¸
    Developer Relations @ js.org ğŸ“
    Open-source maintainer & avid supporter ğŸ’»

  keywords:
    - matt
    - cowley
    - matt cowley
    - ipv4
    - matt ipv4
    - mattipv4
    - matt ipv4 cowley
    - matt (ipv4) cowley
    - matt website
    - matt ipv4 website
    - ipv4 website
    - matt site
    - matt ipv4 site
    - ipv4 site
    - community
    - community management
    - community manager
    - open source
    - open-source
    - engineer
    - web dev
    - web development
    - web developer
    - frontend developer
    - backend developer
    - fullstack developer
    - frontend engineer
    - backend engineer
    - fullstack engineer
    - theatre
    - theater
    - technical
    - technician
    - tech
    - theatre technician
    - theater technician
    - theatre tech
    - theater tech

  banner: https://assets.mattcowley.co.uk/header/header.png
  icon: https://assets.mattcowley.co.uk/head/transp/goggles/head_t_g.png
  color: "#0069ff"
  url: https://mattcowley.co.uk/
  twitter: "@MattIPv4"

google:
  analytics: UA-113826252-1
  adsense:
    client: ca-pub-4266526051230566
    slot: 9114202102

roles:
  - Community Platform Manager @ DigitalOcean ğŸ¦ˆï¸
  - Maintainer of cdnjs.com @ Cloudflare â›…
  - Developer Relations @ js.org ğŸ“
  - Open-source maintainer & avid supporter ğŸ’»

interests:
  - Community Management, Developer Relations, Open-Source Advocacy
  - Software Engineering, Full-stack Development (Node.js, Ruby on Rails, Vue.js)
  - Live Production, Live Broadcasting (Livestreaming, Radio, Theatre)
  - Stage Management, Production Electrics, Lighting

contact:
  email: me@mattcowley.co.uk
  links:
    - title: "**twitter**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://twitter.mattcowley.co.uk/

    - title: "**github**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://github.mattcowley.co.uk/

    - title: "**twitch**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://twitch.mattcowley.co.uk/

    - title: "**linkedin**_.mattcowley.co.uk_"
      username: matt-ipv4-cowley
      url: https://linkedin.mattcowley.co.uk/

    - title: "**sponsors**_.mattcowley.co.uk_"
      username: "@MattIPv4"
      url: https://sponsors.mattcowley.co.uk/

